### ISSUE TITLE
Can you explain a little bit what checkInterval does?

### ISSUE THREAD

**Issue by jfromaniello** [mcavage/node-pooling#11]
It is not clear from the documentation and I couldn't understand this from the code either.

Thank you very much

**Comment by pfmooney** [comment]
It establishes an interval on which the consumer-provided check function is run against pool members to ensure their validity.  Only pool members that are available (allocated but presently unused) are checked.

**Comment by jfromaniello** [comment]
Thank you very much for this very clear explanation, I really appreciated it

**Comment by jfromaniello** [comment]
I think is worth mentioning "idle" here:

It establishes an interval on which the consumer-provided check function is run against **idle members of the pool** to ensure their validity.

right?

**Comment by pfmooney** [comment]
Correct, the `available` list is used at the input:
https://github.com/mcavage/node-pooling/blob/f0756913dfeeb3f006e8c824a670b8485f5d02f2/lib/pool.js#L492

It consists of pool members that have been allocated but are not presently acquired by a consumer.
