### ISSUE TITLE
Queued acquire requests not handled after creation error

### ISSUE THREAD

**Issue by pfmooney** [mcavage/node-pooling#5]
After attempting a failed resource create, the acquire queue is not consulted.  If a release event never fires, the items in the queue will go unprocessed until queue is shutdown.

See: mcavage/node-ldapjs#145

I'll submit a PR soon.

**Comment by pfmooney** [comment]
After a look at the existing tests, I believe it comes down to a question of contract.

Should consumers of pool resources be expected to run release even in the case of errors on resource creation?
If so, I can put a fix into ldapjs.  If not, the pool should consult the queue for pending requests after failure.

Let me know which approach you prefer.

**Comment by pfmooney** [comment]
I don't think even a call to release will cause queue items to be processed unless it's performed for a successfully created client.

Potential fix: pfmooney/node-pooling@2b65b118644d42c83179be66038da142d92c42fd

**Comment by mcavage** [comment]
Hey Patrick - the link to your potential fix 404's. 

I don't think pool consumers should need to call `release` when creating underlying clients though - that seems wrong.

**Comment by pfmooney** [comment]
Sorry, link fixed.

**Comment by mcavage** [comment]
great -thanks!

**Comment by mcavage** [comment]
(oh, and that LGTM)
